/*!
    \file  gtkglut_stroke_mono_roman.c
    \brief GtkGLUT Monospace Roman stroke font definition.
*/

/*
 * GtkGLUT Monospace Roman stroke font definition.
 *
 * Copyright (c) 2008 Jan Friesse. All Rights Reserved.
 * Written by Jan Friesse, <jfriesse@gmail.comt>
 * Creation date: Sun Mar 16 2008
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * PAWEL W. OLSZTA BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Except as contained in this notice, the name of Jan Friesse shall not be
 * used in advertising or otherwise to promote the sale, use or other dealings in
 * this Software without prior written authorization from Jan Friesse.
 *
 * Based on modified FreeGLUT code (freeglut_stroke_mono_roman.c). See COPYING file.
 */

/*
 * freeglut_stroke_mono_roman.c
 *
 * freeglut Monospace Roman stroke font definition
 *
 * Copyright (c) 1999-2000 Pawel W. Olszta. All Rights Reserved.
 * Written by Pawel W. Olszta, <olszta@sourceforge.net>
 * Creation date: Thu Dec 16 1999
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * PAWEL W. OLSZTA BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */


/* This file has been automatically generated by the genstroke utility. */

#include "GL/gtkglut.h"
#include "gtkglut_internal.h"

/* char: 0x20 */

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch32st[] =
{
  { 0, NULL }
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch32 = {104.762f,0,__gtkglut_ch32st};

/* char: 0x21 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch33st0[] =
{
 {52.381f,100.0f},
 {52.381f,33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch33st1[] =
{
 {52.381f,9.5238f},
 {47.6191f,4.7619f},
 {52.381f,0.0f},
 {57.1429f,4.7619f},
 {52.381f,9.5238f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch33st[] =
{
 {2,__gtkglut_ch33st0},
 {5,__gtkglut_ch33st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch33 = {104.762f,2,__gtkglut_ch33st};

/* char: 0x22 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch34st0[] =
{
 {33.3334f,100.0f},
 {33.3334f,66.6667f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch34st1[] =
{
 {71.4286f,100.0f},
 {71.4286f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch34st[] =
{
 {2,__gtkglut_ch34st0},
 {2,__gtkglut_ch34st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch34 = {104.762f,2,__gtkglut_ch34st};

/* char: 0x23 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch35st0[] =
{
 {54.7619f,119.048f},
 {21.4286f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch35st1[] =
{
 {83.3334f,119.048f},
 {50.0f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch35st2[] =
{
 {21.4286f,57.1429f},
 {88.0952f,57.1429f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch35st3[] =
{
 {16.6667f,28.5714f},
 {83.3334f,28.5714f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch35st[] =
{
 {2,__gtkglut_ch35st0},
 {2,__gtkglut_ch35st1},
 {2,__gtkglut_ch35st2},
 {2,__gtkglut_ch35st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch35 = {104.762f,4,__gtkglut_ch35st};

/* char: 0x24 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch36st0[] =
{
 {42.8571f,119.048f},
 {42.8571f,-19.0476f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch36st1[] =
{
 {61.9047f,119.048f},
 {61.9047f,-19.0476f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch36st2[] =
{
 {85.7143f,85.7143f},
 {76.1905f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f},
 {28.5714f,95.2381f},
 {19.0476f,85.7143f},
 {19.0476f,76.1905f},
 {23.8095f,66.6667f},
 {28.5714f,61.9048f},
 {38.0952f,57.1429f},
 {66.6666f,47.619f},
 {76.1905f,42.8571f},
 {80.9524f,38.0952f},
 {85.7143f,28.5714f},
 {85.7143f,14.2857f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {19.0476f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch36st[] =
{
 {2,__gtkglut_ch36st0},
 {2,__gtkglut_ch36st1},
 {20,__gtkglut_ch36st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch36 = {104.762f,3,__gtkglut_ch36st};

/* char: 0x25 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch37st0[] =
{
 {95.2381f,100.0f},
 {9.5238f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch37st1[] =
{
 {33.3333f,100.0f},
 {42.8571f,90.4762f},
 {42.8571f,80.9524f},
 {38.0952f,71.4286f},
 {28.5714f,66.6667f},
 {19.0476f,66.6667f},
 {9.5238f,76.1905f},
 {9.5238f,85.7143f},
 {14.2857f,95.2381f},
 {23.8095f,100.0f},
 {33.3333f,100.0f},
 {42.8571f,95.2381f},
 {57.1428f,90.4762f},
 {71.4286f,90.4762f},
 {85.7143f,95.2381f},
 {95.2381f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch37st2[] =
{
 {76.1905f,33.3333f},
 {66.6667f,28.5714f},
 {61.9048f,19.0476f},
 {61.9048f,9.5238f},
 {71.4286f,0.0f},
 {80.9524f,0.0f},
 {90.4762f,4.7619f},
 {95.2381f,14.2857f},
 {95.2381f,23.8095f},
 {85.7143f,33.3333f},
 {76.1905f,33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch37st[] =
{
 {2,__gtkglut_ch37st0},
 {16,__gtkglut_ch37st1},
 {11,__gtkglut_ch37st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch37 = {104.762f,3,__gtkglut_ch37st};

/* char: 0x26 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch38st0[] =
{
 {100.0f,57.1429f},
 {100.0f,61.9048f},
 {95.2381f,66.6667f},
 {90.4762f,66.6667f},
 {85.7143f,61.9048f},
 {80.9524f,52.381f},
 {71.4286f,28.5714f},
 {61.9048f,14.2857f},
 {52.3809f,4.7619f},
 {42.8571f,0.0f},
 {23.8095f,0.0f},
 {14.2857f,4.7619f},
 {9.5238f,9.5238f},
 {4.7619f,19.0476f},
 {4.7619f,28.5714f},
 {9.5238f,38.0952f},
 {14.2857f,42.8571f},
 {47.619f,61.9048f},
 {52.3809f,66.6667f},
 {57.1429f,76.1905f},
 {57.1429f,85.7143f},
 {52.3809f,95.2381f},
 {42.8571f,100.0f},
 {33.3333f,95.2381f},
 {28.5714f,85.7143f},
 {28.5714f,76.1905f},
 {33.3333f,61.9048f},
 {42.8571f,47.619f},
 {66.6667f,14.2857f},
 {76.1905f,4.7619f},
 {85.7143f,0.0f},
 {95.2381f,0.0f},
 {100.0f,4.7619f},
 {100.0f,9.5238f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch38st[] =
{
 {34,__gtkglut_ch38st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch38 = {104.762f,1,__gtkglut_ch38st};

/* char: 0x27 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch39st0[] =
{
 {52.381f,100.0f},
 {52.381f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch39st[] =
{
 {2,__gtkglut_ch39st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch39 = {104.762f,1,__gtkglut_ch39st};

/* char: 0x28 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch40st0[] =
{
 {69.0476f,119.048f},
 {59.5238f,109.524f},
 {50.0f,95.2381f},
 {40.4762f,76.1905f},
 {35.7143f,52.381f},
 {35.7143f,33.3333f},
 {40.4762f,9.5238f},
 {50.0f,-9.5238f},
 {59.5238f,-23.8095f},
 {69.0476f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch40st[] =
{
 {10,__gtkglut_ch40st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch40 = {104.762f,1,__gtkglut_ch40st};

/* char: 0x29 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch41st0[] =
{
 {35.7143f,119.048f},
 {45.2381f,109.524f},
 {54.7619f,95.2381f},
 {64.2857f,76.1905f},
 {69.0476f,52.381f},
 {69.0476f,33.3333f},
 {64.2857f,9.5238f},
 {54.7619f,-9.5238f},
 {45.2381f,-23.8095f},
 {35.7143f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch41st[] =
{
 {10,__gtkglut_ch41st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch41 = {104.762f,1,__gtkglut_ch41st};

/* char: 0x2a */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch42st0[] =
{
 {52.381f,71.4286f},
 {52.381f,14.2857f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch42st1[] =
{
 {28.5715f,57.1429f},
 {76.1905f,28.5714f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch42st2[] =
{
 {76.1905f,57.1429f},
 {28.5715f,28.5714f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch42st[] =
{
 {2,__gtkglut_ch42st0},
 {2,__gtkglut_ch42st1},
 {2,__gtkglut_ch42st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch42 = {104.762f,3,__gtkglut_ch42st};

/* char: 0x2b */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch43st0[] =
{
 {52.3809f,85.7143f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch43st1[] =
{
 {9.5238f,42.8571f},
 {95.2381f,42.8571f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch43st[] =
{
 {2,__gtkglut_ch43st0},
 {2,__gtkglut_ch43st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch43 = {104.762f,2,__gtkglut_ch43st};

/* char: 0x2c */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch44st0[] =
{
 {57.1429f,4.7619f},
 {52.381f,0.0f},
 {47.6191f,4.7619f},
 {52.381f,9.5238f},
 {57.1429f,4.7619f},
 {57.1429f,-4.7619f},
 {52.381f,-14.2857f},
 {47.6191f,-19.0476f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch44st[] =
{
 {8,__gtkglut_ch44st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch44 = {104.762f,1,__gtkglut_ch44st};

/* char: 0x2d */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch45st0[] =
{
 {9.5238f,42.8571f},
 {95.2381f,42.8571f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch45st[] =
{
 {2,__gtkglut_ch45st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch45 = {104.762f,1,__gtkglut_ch45st};

/* char: 0x2e */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch46st0[] =
{
 {52.381f,9.5238f},
 {47.6191f,4.7619f},
 {52.381f,0.0f},
 {57.1429f,4.7619f},
 {52.381f,9.5238f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch46st[] =
{
 {5,__gtkglut_ch46st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch46 = {104.762f,1,__gtkglut_ch46st};

/* char: 0x2f */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch47st0[] =
{
 {19.0476f,-14.2857f},
 {85.7143f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch47st[] =
{
 {2,__gtkglut_ch47st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch47 = {104.762f,1,__gtkglut_ch47st};

/* char: 0x30 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch48st0[] =
{
 {47.619f,100.0f},
 {33.3333f,95.2381f},
 {23.8095f,80.9524f},
 {19.0476f,57.1429f},
 {19.0476f,42.8571f},
 {23.8095f,19.0476f},
 {33.3333f,4.7619f},
 {47.619f,0.0f},
 {57.1428f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,19.0476f},
 {85.7143f,42.8571f},
 {85.7143f,57.1429f},
 {80.9524f,80.9524f},
 {71.4286f,95.2381f},
 {57.1428f,100.0f},
 {47.619f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch48st[] =
{
 {17,__gtkglut_ch48st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch48 = {104.762f,1,__gtkglut_ch48st};

/* char: 0x31 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch49st0[] =
{
 {40.4762f,80.9524f},
 {50.0f,85.7143f},
 {64.2857f,100.0f},
 {64.2857f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch49st[] =
{
 {4,__gtkglut_ch49st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch49 = {104.762f,1,__gtkglut_ch49st};

/* char: 0x32 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch50st0[] =
{
 {23.8095f,76.1905f},
 {23.8095f,80.9524f},
 {28.5714f,90.4762f},
 {33.3333f,95.2381f},
 {42.8571f,100.0f},
 {61.9047f,100.0f},
 {71.4286f,95.2381f},
 {76.1905f,90.4762f},
 {80.9524f,80.9524f},
 {80.9524f,71.4286f},
 {76.1905f,61.9048f},
 {66.6666f,47.619f},
 {19.0476f,0.0f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch50st[] =
{
 {14,__gtkglut_ch50st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch50 = {104.762f,1,__gtkglut_ch50st};

/* char: 0x33 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch51st0[] =
{
 {28.5714f,100.0f},
 {80.9524f,100.0f},
 {52.3809f,61.9048f},
 {66.6666f,61.9048f},
 {76.1905f,57.1429f},
 {80.9524f,52.381f},
 {85.7143f,38.0952f},
 {85.7143f,28.5714f},
 {80.9524f,14.2857f},
 {71.4286f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {23.8095f,9.5238f},
 {19.0476f,19.0476f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch51st[] =
{
 {15,__gtkglut_ch51st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch51 = {104.762f,1,__gtkglut_ch51st};

/* char: 0x34 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch52st0[] =
{
 {64.2857f,100.0f},
 {16.6667f,33.3333f},
 {88.0952f,33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch52st1[] =
{
 {64.2857f,100.0f},
 {64.2857f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch52st[] =
{
 {3,__gtkglut_ch52st0},
 {2,__gtkglut_ch52st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch52 = {104.762f,2,__gtkglut_ch52st};

/* char: 0x35 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch53st0[] =
{
 {76.1905f,100.0f},
 {28.5714f,100.0f},
 {23.8095f,57.1429f},
 {28.5714f,61.9048f},
 {42.8571f,66.6667f},
 {57.1428f,66.6667f},
 {71.4286f,61.9048f},
 {80.9524f,52.381f},
 {85.7143f,38.0952f},
 {85.7143f,28.5714f},
 {80.9524f,14.2857f},
 {71.4286f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {23.8095f,9.5238f},
 {19.0476f,19.0476f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch53st[] =
{
 {17,__gtkglut_ch53st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch53 = {104.762f,1,__gtkglut_ch53st};

/* char: 0x36 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch54st0[] =
{
 {78.5714f,85.7143f},
 {73.8096f,95.2381f},
 {59.5238f,100.0f},
 {50.0f,100.0f},
 {35.7143f,95.2381f},
 {26.1905f,80.9524f},
 {21.4286f,57.1429f},
 {21.4286f,33.3333f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {50.0f,0.0f},
 {54.7619f,0.0f},
 {69.0476f,4.7619f},
 {78.5714f,14.2857f},
 {83.3334f,28.5714f},
 {83.3334f,33.3333f},
 {78.5714f,47.619f},
 {69.0476f,57.1429f},
 {54.7619f,61.9048f},
 {50.0f,61.9048f},
 {35.7143f,57.1429f},
 {26.1905f,47.619f},
 {21.4286f,33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch54st[] =
{
 {23,__gtkglut_ch54st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch54 = {104.762f,1,__gtkglut_ch54st};

/* char: 0x37 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch55st0[] =
{
 {85.7143f,100.0f},
 {38.0952f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch55st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch55st[] =
{
 {2,__gtkglut_ch55st0},
 {2,__gtkglut_ch55st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch55 = {104.762f,2,__gtkglut_ch55st};

/* char: 0x38 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch56st0[] =
{
 {42.8571f,100.0f},
 {28.5714f,95.2381f},
 {23.8095f,85.7143f},
 {23.8095f,76.1905f},
 {28.5714f,66.6667f},
 {38.0952f,61.9048f},
 {57.1428f,57.1429f},
 {71.4286f,52.381f},
 {80.9524f,42.8571f},
 {85.7143f,33.3333f},
 {85.7143f,19.0476f},
 {80.9524f,9.5238f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {23.8095f,9.5238f},
 {19.0476f,19.0476f},
 {19.0476f,33.3333f},
 {23.8095f,42.8571f},
 {33.3333f,52.381f},
 {47.619f,57.1429f},
 {66.6666f,61.9048f},
 {76.1905f,66.6667f},
 {80.9524f,76.1905f},
 {80.9524f,85.7143f},
 {76.1905f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch56st[] =
{
 {29,__gtkglut_ch56st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch56 = {104.762f,1,__gtkglut_ch56st};

/* char: 0x39 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch57st0[] =
{
 {83.3334f,66.6667f},
 {78.5714f,52.381f},
 {69.0476f,42.8571f},
 {54.7619f,38.0952f},
 {50.0f,38.0952f},
 {35.7143f,42.8571f},
 {26.1905f,52.381f},
 {21.4286f,66.6667f},
 {21.4286f,71.4286f},
 {26.1905f,85.7143f},
 {35.7143f,95.2381f},
 {50.0f,100.0f},
 {54.7619f,100.0f},
 {69.0476f,95.2381f},
 {78.5714f,85.7143f},
 {83.3334f,66.6667f},
 {83.3334f,42.8571f},
 {78.5714f,19.0476f},
 {69.0476f,4.7619f},
 {54.7619f,0.0f},
 {45.2381f,0.0f},
 {30.9524f,4.7619f},
 {26.1905f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch57st[] =
{
 {23,__gtkglut_ch57st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch57 = {104.762f,1,__gtkglut_ch57st};

/* char: 0x3a */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch58st0[] =
{
 {52.381f,66.6667f},
 {47.6191f,61.9048f},
 {52.381f,57.1429f},
 {57.1429f,61.9048f},
 {52.381f,66.6667f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch58st1[] =
{
 {52.381f,9.5238f},
 {47.6191f,4.7619f},
 {52.381f,0.0f},
 {57.1429f,4.7619f},
 {52.381f,9.5238f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch58st[] =
{
 {5,__gtkglut_ch58st0},
 {5,__gtkglut_ch58st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch58 = {104.762f,2,__gtkglut_ch58st};

/* char: 0x3b */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch59st0[] =
{
 {52.381f,66.6667f},
 {47.6191f,61.9048f},
 {52.381f,57.1429f},
 {57.1429f,61.9048f},
 {52.381f,66.6667f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch59st1[] =
{
 {57.1429f,4.7619f},
 {52.381f,0.0f},
 {47.6191f,4.7619f},
 {52.381f,9.5238f},
 {57.1429f,4.7619f},
 {57.1429f,-4.7619f},
 {52.381f,-14.2857f},
 {47.6191f,-19.0476f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch59st[] =
{
 {5,__gtkglut_ch59st0},
 {8,__gtkglut_ch59st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch59 = {104.762f,2,__gtkglut_ch59st};

/* char: 0x3c */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch60st0[] =
{
 {90.4762f,85.7143f},
 {14.2857f,42.8571f},
 {90.4762f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch60st[] =
{
 {3,__gtkglut_ch60st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch60 = {104.762f,1,__gtkglut_ch60st};

/* char: 0x3d */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch61st0[] =
{
 {9.5238f,57.1429f},
 {95.2381f,57.1429f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch61st1[] =
{
 {9.5238f,28.5714f},
 {95.2381f,28.5714f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch61st[] =
{
 {2,__gtkglut_ch61st0},
 {2,__gtkglut_ch61st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch61 = {104.762f,2,__gtkglut_ch61st};

/* char: 0x3e */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch62st0[] =
{
 {14.2857f,85.7143f},
 {90.4762f,42.8571f},
 {14.2857f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch62st[] =
{
 {3,__gtkglut_ch62st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch62 = {104.762f,1,__gtkglut_ch62st};

/* char: 0x3f */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch63st0[] =
{
 {23.8095f,76.1905f},
 {23.8095f,80.9524f},
 {28.5714f,90.4762f},
 {33.3333f,95.2381f},
 {42.8571f,100.0f},
 {61.9047f,100.0f},
 {71.4285f,95.2381f},
 {76.1905f,90.4762f},
 {80.9524f,80.9524f},
 {80.9524f,71.4286f},
 {76.1905f,61.9048f},
 {71.4285f,57.1429f},
 {52.3809f,47.619f},
 {52.3809f,33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch63st1[] =
{
 {52.3809f,9.5238f},
 {47.619f,4.7619f},
 {52.3809f,0.0f},
 {57.1428f,4.7619f},
 {52.3809f,9.5238f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch63st[] =
{
 {14,__gtkglut_ch63st0},
 {5,__gtkglut_ch63st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch63 = {104.762f,2,__gtkglut_ch63st};

/* char: 0x40 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch64st0[] =
{
 {64.2857f,52.381f},
 {54.7619f,57.1429f},
 {45.2381f,57.1429f},
 {40.4762f,47.619f},
 {40.4762f,42.8571f},
 {45.2381f,33.3333f},
 {54.7619f,33.3333f},
 {64.2857f,38.0952f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch64st1[] =
{
 {64.2857f,57.1429f},
 {64.2857f,38.0952f},
 {69.0476f,33.3333f},
 {78.5714f,33.3333f},
 {83.3334f,42.8571f},
 {83.3334f,47.619f},
 {78.5714f,61.9048f},
 {69.0476f,71.4286f},
 {54.7619f,76.1905f},
 {50.0f,76.1905f},
 {35.7143f,71.4286f},
 {26.1905f,61.9048f},
 {21.4286f,47.619f},
 {21.4286f,42.8571f},
 {26.1905f,28.5714f},
 {35.7143f,19.0476f},
 {50.0f,14.2857f},
 {54.7619f,14.2857f},
 {69.0476f,19.0476f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch64st[] =
{
 {8,__gtkglut_ch64st0},
 {19,__gtkglut_ch64st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch64 = {104.762f,2,__gtkglut_ch64st};

/* char: 0x41 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch65st0[] =
{
 {52.3809f,100.0f},
 {14.2857f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch65st1[] =
{
 {52.3809f,100.0f},
 {90.4762f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch65st2[] =
{
 {28.5714f,33.3333f},
 {76.1905f,33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch65st[] =
{
 {2,__gtkglut_ch65st0},
 {2,__gtkglut_ch65st1},
 {2,__gtkglut_ch65st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch65 = {104.762f,3,__gtkglut_ch65st};

/* char: 0x42 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch66st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch66st1[] =
{
 {19.0476f,100.0f},
 {61.9047f,100.0f},
 {76.1905f,95.2381f},
 {80.9524f,90.4762f},
 {85.7143f,80.9524f},
 {85.7143f,71.4286f},
 {80.9524f,61.9048f},
 {76.1905f,57.1429f},
 {61.9047f,52.381f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch66st2[] =
{
 {19.0476f,52.381f},
 {61.9047f,52.381f},
 {76.1905f,47.619f},
 {80.9524f,42.8571f},
 {85.7143f,33.3333f},
 {85.7143f,19.0476f},
 {80.9524f,9.5238f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch66st[] =
{
 {2,__gtkglut_ch66st0},
 {9,__gtkglut_ch66st1},
 {10,__gtkglut_ch66st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch66 = {104.762f,3,__gtkglut_ch66st};

/* char: 0x43 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch67st0[] =
{
 {88.0952f,76.1905f},
 {83.3334f,85.7143f},
 {73.8096f,95.2381f},
 {64.2857f,100.0f},
 {45.2381f,100.0f},
 {35.7143f,95.2381f},
 {26.1905f,85.7143f},
 {21.4286f,76.1905f},
 {16.6667f,61.9048f},
 {16.6667f,38.0952f},
 {21.4286f,23.8095f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {45.2381f,0.0f},
 {64.2857f,0.0f},
 {73.8096f,4.7619f},
 {83.3334f,14.2857f},
 {88.0952f,23.8095f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch67st[] =
{
 {18,__gtkglut_ch67st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch67 = {104.762f,1,__gtkglut_ch67st};

/* char: 0x44 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch68st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch68st1[] =
{
 {19.0476f,100.0f},
 {52.3809f,100.0f},
 {66.6666f,95.2381f},
 {76.1905f,85.7143f},
 {80.9524f,76.1905f},
 {85.7143f,61.9048f},
 {85.7143f,38.0952f},
 {80.9524f,23.8095f},
 {76.1905f,14.2857f},
 {66.6666f,4.7619f},
 {52.3809f,0.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch68st[] =
{
 {2,__gtkglut_ch68st0},
 {12,__gtkglut_ch68st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch68 = {104.762f,2,__gtkglut_ch68st};

/* char: 0x45 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch69st0[] =
{
 {21.4286f,100.0f},
 {21.4286f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch69st1[] =
{
 {21.4286f,100.0f},
 {83.3334f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch69st2[] =
{
 {21.4286f,52.381f},
 {59.5238f,52.381f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch69st3[] =
{
 {21.4286f,0.0f},
 {83.3334f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch69st[] =
{
 {2,__gtkglut_ch69st0},
 {2,__gtkglut_ch69st1},
 {2,__gtkglut_ch69st2},
 {2,__gtkglut_ch69st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch69 = {104.762f,4,__gtkglut_ch69st};

/* char: 0x46 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch70st0[] =
{
 {21.4286f,100.0f},
 {21.4286f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch70st1[] =
{
 {21.4286f,100.0f},
 {83.3334f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch70st2[] =
{
 {21.4286f,52.381f},
 {59.5238f,52.381f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch70st[] =
{
 {2,__gtkglut_ch70st0},
 {2,__gtkglut_ch70st1},
 {2,__gtkglut_ch70st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch70 = {104.762f,3,__gtkglut_ch70st};

/* char: 0x47 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch71st0[] =
{
 {88.0952f,76.1905f},
 {83.3334f,85.7143f},
 {73.8096f,95.2381f},
 {64.2857f,100.0f},
 {45.2381f,100.0f},
 {35.7143f,95.2381f},
 {26.1905f,85.7143f},
 {21.4286f,76.1905f},
 {16.6667f,61.9048f},
 {16.6667f,38.0952f},
 {21.4286f,23.8095f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {45.2381f,0.0f},
 {64.2857f,0.0f},
 {73.8096f,4.7619f},
 {83.3334f,14.2857f},
 {88.0952f,23.8095f},
 {88.0952f,38.0952f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch71st1[] =
{
 {64.2857f,38.0952f},
 {88.0952f,38.0952f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch71st[] =
{
 {19,__gtkglut_ch71st0},
 {2,__gtkglut_ch71st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch71 = {104.762f,2,__gtkglut_ch71st};

/* char: 0x48 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch72st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch72st1[] =
{
 {85.7143f,100.0f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch72st2[] =
{
 {19.0476f,52.381f},
 {85.7143f,52.381f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch72st[] =
{
 {2,__gtkglut_ch72st0},
 {2,__gtkglut_ch72st1},
 {2,__gtkglut_ch72st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch72 = {104.762f,3,__gtkglut_ch72st};

/* char: 0x49 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch73st0[] =
{
 {52.381f,100.0f},
 {52.381f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch73st[] =
{
 {2,__gtkglut_ch73st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch73 = {104.762f,1,__gtkglut_ch73st};

/* char: 0x4a */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch74st0[] =
{
 {76.1905f,100.0f},
 {76.1905f,23.8095f},
 {71.4286f,9.5238f},
 {66.6667f,4.7619f},
 {57.1429f,0.0f},
 {47.6191f,0.0f},
 {38.0953f,4.7619f},
 {33.3334f,9.5238f},
 {28.5715f,23.8095f},
 {28.5715f,33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch74st[] =
{
 {10,__gtkglut_ch74st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch74 = {104.762f,1,__gtkglut_ch74st};

/* char: 0x4b */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch75st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch75st1[] =
{
 {85.7143f,100.0f},
 {19.0476f,33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch75st2[] =
{
 {42.8571f,57.1429f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch75st[] =
{
 {2,__gtkglut_ch75st0},
 {2,__gtkglut_ch75st1},
 {2,__gtkglut_ch75st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch75 = {104.762f,3,__gtkglut_ch75st};

/* char: 0x4c */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch76st0[] =
{
 {23.8095f,100.0f},
 {23.8095f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch76st1[] =
{
 {23.8095f,0.0f},
 {80.9524f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch76st[] =
{
 {2,__gtkglut_ch76st0},
 {2,__gtkglut_ch76st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch76 = {104.762f,2,__gtkglut_ch76st};

/* char: 0x4d */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch77st0[] =
{
 {14.2857f,100.0f},
 {14.2857f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch77st1[] =
{
 {14.2857f,100.0f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch77st2[] =
{
 {90.4762f,100.0f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch77st3[] =
{
 {90.4762f,100.0f},
 {90.4762f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch77st[] =
{
 {2,__gtkglut_ch77st0},
 {2,__gtkglut_ch77st1},
 {2,__gtkglut_ch77st2},
 {2,__gtkglut_ch77st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch77 = {104.762f,4,__gtkglut_ch77st};

/* char: 0x4e */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch78st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch78st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch78st2[] =
{
 {85.7143f,100.0f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch78st[] =
{
 {2,__gtkglut_ch78st0},
 {2,__gtkglut_ch78st1},
 {2,__gtkglut_ch78st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch78 = {104.762f,3,__gtkglut_ch78st};

/* char: 0x4f */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch79st0[] =
{
 {42.8571f,100.0f},
 {33.3333f,95.2381f},
 {23.8095f,85.7143f},
 {19.0476f,76.1905f},
 {14.2857f,61.9048f},
 {14.2857f,38.0952f},
 {19.0476f,23.8095f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {42.8571f,0.0f},
 {61.9047f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,23.8095f},
 {90.4762f,38.0952f},
 {90.4762f,61.9048f},
 {85.7143f,76.1905f},
 {80.9524f,85.7143f},
 {71.4286f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch79st[] =
{
 {21,__gtkglut_ch79st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch79 = {104.762f,1,__gtkglut_ch79st};

/* char: 0x50 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch80st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch80st1[] =
{
 {19.0476f,100.0f},
 {61.9047f,100.0f},
 {76.1905f,95.2381f},
 {80.9524f,90.4762f},
 {85.7143f,80.9524f},
 {85.7143f,66.6667f},
 {80.9524f,57.1429f},
 {76.1905f,52.381f},
 {61.9047f,47.619f},
 {19.0476f,47.619f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch80st[] =
{
 {2,__gtkglut_ch80st0},
 {10,__gtkglut_ch80st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch80 = {104.762f,2,__gtkglut_ch80st};

/* char: 0x51 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch81st0[] =
{
 {42.8571f,100.0f},
 {33.3333f,95.2381f},
 {23.8095f,85.7143f},
 {19.0476f,76.1905f},
 {14.2857f,61.9048f},
 {14.2857f,38.0952f},
 {19.0476f,23.8095f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {42.8571f,0.0f},
 {61.9047f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,23.8095f},
 {90.4762f,38.0952f},
 {90.4762f,61.9048f},
 {85.7143f,76.1905f},
 {80.9524f,85.7143f},
 {71.4286f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch81st1[] =
{
 {57.1428f,19.0476f},
 {85.7143f,-9.5238f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch81st[] =
{
 {21,__gtkglut_ch81st0},
 {2,__gtkglut_ch81st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch81 = {104.762f,2,__gtkglut_ch81st};

/* char: 0x52 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch82st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch82st1[] =
{
 {19.0476f,100.0f},
 {61.9047f,100.0f},
 {76.1905f,95.2381f},
 {80.9524f,90.4762f},
 {85.7143f,80.9524f},
 {85.7143f,71.4286f},
 {80.9524f,61.9048f},
 {76.1905f,57.1429f},
 {61.9047f,52.381f},
 {19.0476f,52.381f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch82st2[] =
{
 {52.3809f,52.381f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch82st[] =
{
 {2,__gtkglut_ch82st0},
 {10,__gtkglut_ch82st1},
 {2,__gtkglut_ch82st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch82 = {104.762f,3,__gtkglut_ch82st};

/* char: 0x53 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch83st0[] =
{
 {85.7143f,85.7143f},
 {76.1905f,95.2381f},
 {61.9047f,100.0f},
 {42.8571f,100.0f},
 {28.5714f,95.2381f},
 {19.0476f,85.7143f},
 {19.0476f,76.1905f},
 {23.8095f,66.6667f},
 {28.5714f,61.9048f},
 {38.0952f,57.1429f},
 {66.6666f,47.619f},
 {76.1905f,42.8571f},
 {80.9524f,38.0952f},
 {85.7143f,28.5714f},
 {85.7143f,14.2857f},
 {76.1905f,4.7619f},
 {61.9047f,0.0f},
 {42.8571f,0.0f},
 {28.5714f,4.7619f},
 {19.0476f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch83st[] =
{
 {20,__gtkglut_ch83st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch83 = {104.762f,1,__gtkglut_ch83st};

/* char: 0x54 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch84st0[] =
{
 {52.3809f,100.0f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch84st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch84st[] =
{
 {2,__gtkglut_ch84st0},
 {2,__gtkglut_ch84st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch84 = {104.762f,2,__gtkglut_ch84st};

/* char: 0x55 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch85st0[] =
{
 {19.0476f,100.0f},
 {19.0476f,28.5714f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {47.619f,0.0f},
 {57.1428f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,28.5714f},
 {85.7143f,100.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch85st[] =
{
 {10,__gtkglut_ch85st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch85 = {104.762f,1,__gtkglut_ch85st};

/* char: 0x56 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch86st0[] =
{
 {14.2857f,100.0f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch86st1[] =
{
 {90.4762f,100.0f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch86st[] =
{
 {2,__gtkglut_ch86st0},
 {2,__gtkglut_ch86st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch86 = {104.762f,2,__gtkglut_ch86st};

/* char: 0x57 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch87st0[] =
{
 {4.7619f,100.0f},
 {28.5714f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch87st1[] =
{
 {52.3809f,100.0f},
 {28.5714f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch87st2[] =
{
 {52.3809f,100.0f},
 {76.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch87st3[] =
{
 {100.0f,100.0f},
 {76.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch87st[] =
{
 {2,__gtkglut_ch87st0},
 {2,__gtkglut_ch87st1},
 {2,__gtkglut_ch87st2},
 {2,__gtkglut_ch87st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch87 = {104.762f,4,__gtkglut_ch87st};

/* char: 0x58 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch88st0[] =
{
 {19.0476f,100.0f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch88st1[] =
{
 {85.7143f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch88st[] =
{
 {2,__gtkglut_ch88st0},
 {2,__gtkglut_ch88st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch88 = {104.762f,2,__gtkglut_ch88st};

/* char: 0x59 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch89st0[] =
{
 {14.2857f,100.0f},
 {52.3809f,52.381f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch89st1[] =
{
 {90.4762f,100.0f},
 {52.3809f,52.381f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch89st[] =
{
 {3,__gtkglut_ch89st0},
 {2,__gtkglut_ch89st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch89 = {104.762f,2,__gtkglut_ch89st};

/* char: 0x5a */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch90st0[] =
{
 {85.7143f,100.0f},
 {19.0476f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch90st1[] =
{
 {19.0476f,100.0f},
 {85.7143f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch90st2[] =
{
 {19.0476f,0.0f},
 {85.7143f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch90st[] =
{
 {2,__gtkglut_ch90st0},
 {2,__gtkglut_ch90st1},
 {2,__gtkglut_ch90st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch90 = {104.762f,3,__gtkglut_ch90st};

/* char: 0x5b */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch91st0[] =
{
 {35.7143f,119.048f},
 {35.7143f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch91st1[] =
{
 {40.4762f,119.048f},
 {40.4762f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch91st2[] =
{
 {35.7143f,119.048f},
 {69.0476f,119.048f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch91st3[] =
{
 {35.7143f,-33.3333f},
 {69.0476f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch91st[] =
{
 {2,__gtkglut_ch91st0},
 {2,__gtkglut_ch91st1},
 {2,__gtkglut_ch91st2},
 {2,__gtkglut_ch91st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch91 = {104.762f,4,__gtkglut_ch91st};

/* char: 0x5c */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch92st0[] =
{
 {19.0476f,100.0f},
 {85.7143f,-14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch92st[] =
{
 {2,__gtkglut_ch92st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch92 = {104.762f,1,__gtkglut_ch92st};

/* char: 0x5d */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch93st0[] =
{
 {64.2857f,119.048f},
 {64.2857f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch93st1[] =
{
 {69.0476f,119.048f},
 {69.0476f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch93st2[] =
{
 {35.7143f,119.048f},
 {69.0476f,119.048f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch93st3[] =
{
 {35.7143f,-33.3333f},
 {69.0476f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch93st[] =
{
 {2,__gtkglut_ch93st0},
 {2,__gtkglut_ch93st1},
 {2,__gtkglut_ch93st2},
 {2,__gtkglut_ch93st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch93 = {104.762f,4,__gtkglut_ch93st};

/* char: 0x5e */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch94st0[] =
{
 {52.3809f,109.524f},
 {14.2857f,42.8571f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch94st1[] =
{
 {52.3809f,109.524f},
 {90.4762f,42.8571f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch94st[] =
{
 {2,__gtkglut_ch94st0},
 {2,__gtkglut_ch94st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch94 = {104.762f,2,__gtkglut_ch94st};

/* char: 0x5f */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch95st0[] =
{
 {0,-33.3333f},
 {104.762f,-33.3333f},
 {104.762f,-28.5714f},
 {0,-28.5714f},
 {0,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch95st[] =
{
 {5,__gtkglut_ch95st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch95 = {104.762f,1,__gtkglut_ch95st};

/* char: 0x60 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch96st0[] =
{
 {42.8572f,100.0f},
 {66.6667f,71.4286f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch96st1[] =
{
 {42.8572f,100.0f},
 {38.0953f,95.2381f},
 {66.6667f,71.4286f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch96st[] =
{
 {2,__gtkglut_ch96st0},
 {3,__gtkglut_ch96st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch96 = {104.762f,2,__gtkglut_ch96st};

/* char: 0x61 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch97st0[] =
{
 {80.9524f,66.6667f},
 {80.9524f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch97st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch97st[] =
{
 {2,__gtkglut_ch97st0},
 {14,__gtkglut_ch97st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch97 = {104.762f,2,__gtkglut_ch97st};

/* char: 0x62 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch98st0[] =
{
 {23.8095f,100.0f},
 {23.8095f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch98st1[] =
{
 {23.8095f,52.381f},
 {33.3333f,61.9048f},
 {42.8571f,66.6667f},
 {57.1428f,66.6667f},
 {66.6666f,61.9048f},
 {76.1905f,52.381f},
 {80.9524f,38.0952f},
 {80.9524f,28.5714f},
 {76.1905f,14.2857f},
 {66.6666f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {33.3333f,4.7619f},
 {23.8095f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch98st[] =
{
 {2,__gtkglut_ch98st0},
 {14,__gtkglut_ch98st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch98 = {104.762f,2,__gtkglut_ch98st};

/* char: 0x63 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch99st0[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch99st[] =
{
 {14,__gtkglut_ch99st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch99 = {104.762f,1,__gtkglut_ch99st};

/* char: 0x64 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch100st0[] =
{
 {80.9524f,100.0f},
 {80.9524f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch100st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch100st[] =
{
 {2,__gtkglut_ch100st0},
 {14,__gtkglut_ch100st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch100 = {104.762f,2,__gtkglut_ch100st};

/* char: 0x65 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch101st0[] =
{
 {23.8095f,38.0952f},
 {80.9524f,38.0952f},
 {80.9524f,47.619f},
 {76.1905f,57.1429f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch101st[] =
{
 {17,__gtkglut_ch101st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch101 = {104.762f,1,__gtkglut_ch101st};

/* char: 0x66 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch102st0[] =
{
 {71.4286f,100.0f},
 {61.9048f,100.0f},
 {52.381f,95.2381f},
 {47.6191f,80.9524f},
 {47.6191f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch102st1[] =
{
 {33.3334f,66.6667f},
 {66.6667f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch102st[] =
{
 {5,__gtkglut_ch102st0},
 {2,__gtkglut_ch102st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch102 = {104.762f,2,__gtkglut_ch102st};

/* char: 0x67 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch103st0[] =
{
 {80.9524f,66.6667f},
 {80.9524f,-9.5238f},
 {76.1905f,-23.8095f},
 {71.4285f,-28.5714f},
 {61.9047f,-33.3333f},
 {47.619f,-33.3333f},
 {38.0952f,-28.5714f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch103st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch103st[] =
{
 {7,__gtkglut_ch103st0},
 {14,__gtkglut_ch103st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch103 = {104.762f,2,__gtkglut_ch103st};

/* char: 0x68 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch104st0[] =
{
 {26.1905f,100.0f},
 {26.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch104st1[] =
{
 {26.1905f,47.619f},
 {40.4762f,61.9048f},
 {50.0f,66.6667f},
 {64.2857f,66.6667f},
 {73.8095f,61.9048f},
 {78.5715f,47.619f},
 {78.5715f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch104st[] =
{
 {2,__gtkglut_ch104st0},
 {7,__gtkglut_ch104st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch104 = {104.762f,2,__gtkglut_ch104st};

/* char: 0x69 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch105st0[] =
{
 {47.6191f,100.0f},
 {52.381f,95.2381f},
 {57.1429f,100.0f},
 {52.381f,104.762f},
 {47.6191f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch105st1[] =
{
 {52.381f,66.6667f},
 {52.381f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch105st[] =
{
 {5,__gtkglut_ch105st0},
 {2,__gtkglut_ch105st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch105 = {104.762f,2,__gtkglut_ch105st};

/* char: 0x6a */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch106st0[] =
{
 {57.1429f,100.0f},
 {61.9048f,95.2381f},
 {66.6667f,100.0f},
 {61.9048f,104.762f},
 {57.1429f,100.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch106st1[] =
{
 {61.9048f,66.6667f},
 {61.9048f,-14.2857f},
 {57.1429f,-28.5714f},
 {47.6191f,-33.3333f},
 {38.0953f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch106st[] =
{
 {5,__gtkglut_ch106st0},
 {5,__gtkglut_ch106st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch106 = {104.762f,2,__gtkglut_ch106st};

/* char: 0x6b */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch107st0[] =
{
 {26.1905f,100.0f},
 {26.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch107st1[] =
{
 {73.8095f,66.6667f},
 {26.1905f,19.0476f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch107st2[] =
{
 {45.2381f,38.0952f},
 {78.5715f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch107st[] =
{
 {2,__gtkglut_ch107st0},
 {2,__gtkglut_ch107st1},
 {2,__gtkglut_ch107st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch107 = {104.762f,3,__gtkglut_ch107st};

/* char: 0x6c */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch108st0[] =
{
 {52.381f,100.0f},
 {52.381f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch108st[] =
{
 {2,__gtkglut_ch108st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch108 = {104.762f,1,__gtkglut_ch108st};

/* char: 0x6d */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch109st0[] =
{
 {0,66.6667f},
 {0,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch109st1[] =
{
 {0,47.619f},
 {14.2857f,61.9048f},
 {23.8095f,66.6667f},
 {38.0952f,66.6667f},
 {47.619f,61.9048f},
 {52.381f,47.619f},
 {52.381f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch109st2[] =
{
 {52.381f,47.619f},
 {66.6667f,61.9048f},
 {76.1905f,66.6667f},
 {90.4762f,66.6667f},
 {100.0f,61.9048f},
 {104.762f,47.619f},
 {104.762f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch109st[] =
{
 {2,__gtkglut_ch109st0},
 {7,__gtkglut_ch109st1},
 {7,__gtkglut_ch109st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch109 = {104.762f,3,__gtkglut_ch109st};

/* char: 0x6e */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch110st0[] =
{
 {26.1905f,66.6667f},
 {26.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch110st1[] =
{
 {26.1905f,47.619f},
 {40.4762f,61.9048f},
 {50.0f,66.6667f},
 {64.2857f,66.6667f},
 {73.8095f,61.9048f},
 {78.5715f,47.619f},
 {78.5715f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch110st[] =
{
 {2,__gtkglut_ch110st0},
 {7,__gtkglut_ch110st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch110 = {104.762f,2,__gtkglut_ch110st};

/* char: 0x6f */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch111st0[] =
{
 {45.2381f,66.6667f},
 {35.7143f,61.9048f},
 {26.1905f,52.381f},
 {21.4286f,38.0952f},
 {21.4286f,28.5714f},
 {26.1905f,14.2857f},
 {35.7143f,4.7619f},
 {45.2381f,0.0f},
 {59.5238f,0.0f},
 {69.0476f,4.7619f},
 {78.5714f,14.2857f},
 {83.3334f,28.5714f},
 {83.3334f,38.0952f},
 {78.5714f,52.381f},
 {69.0476f,61.9048f},
 {59.5238f,66.6667f},
 {45.2381f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch111st[] =
{
 {17,__gtkglut_ch111st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch111 = {104.762f,1,__gtkglut_ch111st};

/* char: 0x70 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch112st0[] =
{
 {23.8095f,66.6667f},
 {23.8095f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch112st1[] =
{
 {23.8095f,52.381f},
 {33.3333f,61.9048f},
 {42.8571f,66.6667f},
 {57.1428f,66.6667f},
 {66.6666f,61.9048f},
 {76.1905f,52.381f},
 {80.9524f,38.0952f},
 {80.9524f,28.5714f},
 {76.1905f,14.2857f},
 {66.6666f,4.7619f},
 {57.1428f,0.0f},
 {42.8571f,0.0f},
 {33.3333f,4.7619f},
 {23.8095f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch112st[] =
{
 {2,__gtkglut_ch112st0},
 {14,__gtkglut_ch112st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch112 = {104.762f,2,__gtkglut_ch112st};

/* char: 0x71 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch113st0[] =
{
 {80.9524f,66.6667f},
 {80.9524f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch113st1[] =
{
 {80.9524f,52.381f},
 {71.4285f,61.9048f},
 {61.9047f,66.6667f},
 {47.619f,66.6667f},
 {38.0952f,61.9048f},
 {28.5714f,52.381f},
 {23.8095f,38.0952f},
 {23.8095f,28.5714f},
 {28.5714f,14.2857f},
 {38.0952f,4.7619f},
 {47.619f,0.0f},
 {61.9047f,0.0f},
 {71.4285f,4.7619f},
 {80.9524f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch113st[] =
{
 {2,__gtkglut_ch113st0},
 {14,__gtkglut_ch113st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch113 = {104.762f,2,__gtkglut_ch113st};

/* char: 0x72 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch114st0[] =
{
 {33.3334f,66.6667f},
 {33.3334f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch114st1[] =
{
 {33.3334f,38.0952f},
 {38.0953f,52.381f},
 {47.6191f,61.9048f},
 {57.1429f,66.6667f},
 {71.4286f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch114st[] =
{
 {2,__gtkglut_ch114st0},
 {5,__gtkglut_ch114st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch114 = {104.762f,2,__gtkglut_ch114st};

/* char: 0x73 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch115st0[] =
{
 {78.5715f,52.381f},
 {73.8095f,61.9048f},
 {59.5238f,66.6667f},
 {45.2381f,66.6667f},
 {30.9524f,61.9048f},
 {26.1905f,52.381f},
 {30.9524f,42.8571f},
 {40.4762f,38.0952f},
 {64.2857f,33.3333f},
 {73.8095f,28.5714f},
 {78.5715f,19.0476f},
 {78.5715f,14.2857f},
 {73.8095f,4.7619f},
 {59.5238f,0.0f},
 {45.2381f,0.0f},
 {30.9524f,4.7619f},
 {26.1905f,14.2857f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch115st[] =
{
 {17,__gtkglut_ch115st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch115 = {104.762f,1,__gtkglut_ch115st};

/* char: 0x74 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch116st0[] =
{
 {47.6191f,100.0f},
 {47.6191f,19.0476f},
 {52.381f,4.7619f},
 {61.9048f,0.0f},
 {71.4286f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch116st1[] =
{
 {33.3334f,66.6667f},
 {66.6667f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch116st[] =
{
 {5,__gtkglut_ch116st0},
 {2,__gtkglut_ch116st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch116 = {104.762f,2,__gtkglut_ch116st};

/* char: 0x75 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch117st0[] =
{
 {26.1905f,66.6667f},
 {26.1905f,19.0476f},
 {30.9524f,4.7619f},
 {40.4762f,0.0f},
 {54.7619f,0.0f},
 {64.2857f,4.7619f},
 {78.5715f,19.0476f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch117st1[] =
{
 {78.5715f,66.6667f},
 {78.5715f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch117st[] =
{
 {7,__gtkglut_ch117st0},
 {2,__gtkglut_ch117st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch117 = {104.762f,2,__gtkglut_ch117st};

/* char: 0x76 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch118st0[] =
{
 {23.8095f,66.6667f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch118st1[] =
{
 {80.9524f,66.6667f},
 {52.3809f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch118st[] =
{
 {2,__gtkglut_ch118st0},
 {2,__gtkglut_ch118st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch118 = {104.762f,2,__gtkglut_ch118st};

/* char: 0x77 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch119st0[] =
{
 {14.2857f,66.6667f},
 {33.3333f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch119st1[] =
{
 {52.3809f,66.6667f},
 {33.3333f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch119st2[] =
{
 {52.3809f,66.6667f},
 {71.4286f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch119st3[] =
{
 {90.4762f,66.6667f},
 {71.4286f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch119st[] =
{
 {2,__gtkglut_ch119st0},
 {2,__gtkglut_ch119st1},
 {2,__gtkglut_ch119st2},
 {2,__gtkglut_ch119st3}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch119 = {104.762f,4,__gtkglut_ch119st};

/* char: 0x78 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch120st0[] =
{
 {26.1905f,66.6667f},
 {78.5715f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch120st1[] =
{
 {78.5715f,66.6667f},
 {26.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch120st[] =
{
 {2,__gtkglut_ch120st0},
 {2,__gtkglut_ch120st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch120 = {104.762f,2,__gtkglut_ch120st};

/* char: 0x79 */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch121st0[] =
{
 {26.1905f,66.6667f},
 {54.7619f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch121st1[] =
{
 {83.3334f,66.6667f},
 {54.7619f,0.0f},
 {45.2381f,-19.0476f},
 {35.7143f,-28.5714f},
 {26.1905f,-33.3333f},
 {21.4286f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch121st[] =
{
 {2,__gtkglut_ch121st0},
 {6,__gtkglut_ch121st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch121 = {104.762f,2,__gtkglut_ch121st};

/* char: 0x7a */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch122st0[] =
{
 {78.5715f,66.6667f},
 {26.1905f,0.0f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch122st1[] =
{
 {26.1905f,66.6667f},
 {78.5715f,66.6667f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch122st2[] =
{
 {26.1905f,0.0f},
 {78.5715f,0.0f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch122st[] =
{
 {2,__gtkglut_ch122st0},
 {2,__gtkglut_ch122st1},
 {2,__gtkglut_ch122st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch122 = {104.762f,3,__gtkglut_ch122st};

/* char: 0x7b */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch123st0[] =
{
 {64.2857f,119.048f},
 {54.7619f,114.286f},
 {50.0f,109.524f},
 {45.2381f,100.0f},
 {45.2381f,90.4762f},
 {50.0f,80.9524f},
 {54.7619f,76.1905f},
 {59.5238f,66.6667f},
 {59.5238f,57.1429f},
 {50.0f,47.619f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch123st1[] =
{
 {54.7619f,114.286f},
 {50.0f,104.762f},
 {50.0f,95.2381f},
 {54.7619f,85.7143f},
 {59.5238f,80.9524f},
 {64.2857f,71.4286f},
 {64.2857f,61.9048f},
 {59.5238f,52.381f},
 {40.4762f,42.8571f},
 {59.5238f,33.3333f},
 {64.2857f,23.8095f},
 {64.2857f,14.2857f},
 {59.5238f,4.7619f},
 {54.7619f,0.0f},
 {50.0f,-9.5238f},
 {50.0f,-19.0476f},
 {54.7619f,-28.5714f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch123st2[] =
{
 {50.0f,38.0952f},
 {59.5238f,28.5714f},
 {59.5238f,19.0476f},
 {54.7619f,9.5238f},
 {50.0f,4.7619f},
 {45.2381f,-4.7619f},
 {45.2381f,-14.2857f},
 {50.0f,-23.8095f},
 {54.7619f,-28.5714f},
 {64.2857f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch123st[] =
{
 {10,__gtkglut_ch123st0},
 {17,__gtkglut_ch123st1},
 {10,__gtkglut_ch123st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch123 = {104.762f,3,__gtkglut_ch123st};

/* char: 0x7c */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch124st0[] =
{
 {52.381f,119.048f},
 {52.381f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch124st[] =
{
 {2,__gtkglut_ch124st0}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch124 = {104.762f,1,__gtkglut_ch124st};

/* char: 0x7d */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch125st0[] =
{
 {40.4762f,119.048f},
 {50.0f,114.286f},
 {54.7619f,109.524f},
 {59.5238f,100.0f},
 {59.5238f,90.4762f},
 {54.7619f,80.9524f},
 {50.0f,76.1905f},
 {45.2381f,66.6667f},
 {45.2381f,57.1429f},
 {54.7619f,47.619f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch125st1[] =
{
 {50.0f,114.286f},
 {54.7619f,104.762f},
 {54.7619f,95.2381f},
 {50.0f,85.7143f},
 {45.2381f,80.9524f},
 {40.4762f,71.4286f},
 {40.4762f,61.9048f},
 {45.2381f,52.381f},
 {64.2857f,42.8571f},
 {45.2381f,33.3333f},
 {40.4762f,23.8095f},
 {40.4762f,14.2857f},
 {45.2381f,4.7619f},
 {50.0f,0.0f},
 {54.7619f,-9.5238f},
 {54.7619f,-19.0476f},
 {50.0f,-28.5714f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch125st2[] =
{
 {54.7619f,38.0952f},
 {45.2381f,28.5714f},
 {45.2381f,19.0476f},
 {50.0f,9.5238f},
 {54.7619f,4.7619f},
 {59.5238f,-4.7619f},
 {59.5238f,-14.2857f},
 {54.7619f,-23.8095f},
 {50.0f,-28.5714f},
 {40.4762f,-33.3333f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch125st[] =
{
 {10,__gtkglut_ch125st0},
 {17,__gtkglut_ch125st1},
 {10,__gtkglut_ch125st2}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch125 = {104.762f,3,__gtkglut_ch125st};

/* char: 0x7e */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch126st0[] =
{
 {9.5238f,28.5714f},
 {9.5238f,38.0952f},
 {14.2857f,52.381f},
 {23.8095f,57.1429f},
 {33.3333f,57.1429f},
 {42.8571f,52.381f},
 {61.9048f,38.0952f},
 {71.4286f,33.3333f},
 {80.9524f,33.3333f},
 {90.4762f,38.0952f},
 {95.2381f,47.619f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch126st1[] =
{
 {9.5238f,38.0952f},
 {14.2857f,47.619f},
 {23.8095f,52.381f},
 {33.3333f,52.381f},
 {42.8571f,47.619f},
 {61.9048f,33.3333f},
 {71.4286f,28.5714f},
 {80.9524f,28.5714f},
 {90.4762f,33.3333f},
 {95.2381f,47.619f},
 {95.2381f,57.1429f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch126st[] =
{
 {11,__gtkglut_ch126st0},
 {11,__gtkglut_ch126st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch126 = {104.762f,2,__gtkglut_ch126st};

/* char: 0x7f */

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch127st0[] =
{
 {71.4286f,100.0f},
 {33.3333f,-33.3333f}
};

static const __gtkglut_SFG_StrokeVertex __gtkglut_ch127st1[] =
{
 {47.619f,66.6667f},
 {33.3333f,61.9048f},
 {23.8095f,52.381f},
 {19.0476f,38.0952f},
 {19.0476f,23.8095f},
 {23.8095f,14.2857f},
 {33.3333f,4.7619f},
 {47.619f,0.0f},
 {57.1428f,0.0f},
 {71.4286f,4.7619f},
 {80.9524f,14.2857f},
 {85.7143f,28.5714f},
 {85.7143f,42.8571f},
 {80.9524f,52.381f},
 {71.4286f,61.9048f},
 {57.1428f,66.6667f},
 {47.619f,66.6667f}
};

static const __gtkglut_SFG_StrokeStrip __gtkglut_ch127st[] =
{
 {2,__gtkglut_ch127st0},
 {17,__gtkglut_ch127st1}
};

static const __gtkglut_SFG_StrokeChar __gtkglut_ch127 = {104.762f,2,__gtkglut_ch127st};

static const __gtkglut_SFG_StrokeChar *__gtkglut_chars[] =
{
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 &__gtkglut_ch32, &__gtkglut_ch33, &__gtkglut_ch34, &__gtkglut_ch35, &__gtkglut_ch36, &__gtkglut_ch37, &__gtkglut_ch38, &__gtkglut_ch39,
 &__gtkglut_ch40, &__gtkglut_ch41, &__gtkglut_ch42, &__gtkglut_ch43, &__gtkglut_ch44, &__gtkglut_ch45, &__gtkglut_ch46, &__gtkglut_ch47,
 &__gtkglut_ch48, &__gtkglut_ch49, &__gtkglut_ch50, &__gtkglut_ch51, &__gtkglut_ch52, &__gtkglut_ch53, &__gtkglut_ch54, &__gtkglut_ch55,
 &__gtkglut_ch56, &__gtkglut_ch57, &__gtkglut_ch58, &__gtkglut_ch59, &__gtkglut_ch60, &__gtkglut_ch61, &__gtkglut_ch62, &__gtkglut_ch63,
 &__gtkglut_ch64, &__gtkglut_ch65, &__gtkglut_ch66, &__gtkglut_ch67, &__gtkglut_ch68, &__gtkglut_ch69, &__gtkglut_ch70, &__gtkglut_ch71,
 &__gtkglut_ch72, &__gtkglut_ch73, &__gtkglut_ch74, &__gtkglut_ch75, &__gtkglut_ch76, &__gtkglut_ch77, &__gtkglut_ch78, &__gtkglut_ch79,
 &__gtkglut_ch80, &__gtkglut_ch81, &__gtkglut_ch82, &__gtkglut_ch83, &__gtkglut_ch84, &__gtkglut_ch85, &__gtkglut_ch86, &__gtkglut_ch87,
 &__gtkglut_ch88, &__gtkglut_ch89, &__gtkglut_ch90, &__gtkglut_ch91, &__gtkglut_ch92, &__gtkglut_ch93, &__gtkglut_ch94, &__gtkglut_ch95,
 &__gtkglut_ch96, &__gtkglut_ch97, &__gtkglut_ch98, &__gtkglut_ch99, &__gtkglut_ch100, &__gtkglut_ch101, &__gtkglut_ch102, &__gtkglut_ch103,
 &__gtkglut_ch104, &__gtkglut_ch105, &__gtkglut_ch106, &__gtkglut_ch107, &__gtkglut_ch108, &__gtkglut_ch109, &__gtkglut_ch110, &__gtkglut_ch111,
 &__gtkglut_ch112, &__gtkglut_ch113, &__gtkglut_ch114, &__gtkglut_ch115, &__gtkglut_ch116, &__gtkglut_ch117, &__gtkglut_ch118, &__gtkglut_ch119,
 &__gtkglut_ch120, &__gtkglut_ch121, &__gtkglut_ch122, &__gtkglut_ch123, &__gtkglut_ch124, &__gtkglut_ch125, &__gtkglut_ch126, &__gtkglut_ch127
};

__gtkglut_SFG_StrokeFont __gtkglut_fgStrokeMonoRoman = {"MonoRoman",128,152.381f,__gtkglut_chars};
